
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 15:17:51 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 36;
  public static final int CONST = 24;
  public static final int CHAR = 16;
  public static final int NOTEQUAL = 42;
  public static final int GREATER = 43;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 32;
  public static final int LESS = 45;
  public static final int MINUS = 38;
  public static final int RPAREN = 7;
  public static final int RECORD = 29;
  public static final int LESSEQUAL = 46;
  public static final int BOOL = 17;
  public static final int COMMA = 11;
  public static final int CLASS = 27;
  public static final int EQUALEQUAL = 41;
  public static final int DIV = 48;
  public static final int PIPEPIPE = 39;
  public static final int PLUS = 10;
  public static final int IF = 18;
  public static final int THIS = 21;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 37;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 50;
  public static final int SUPER = 22;
  public static final int error = 1;
  public static final int MUL = 47;
  public static final int MOD = 49;
  public static final int NUMBER = 14;
  public static final int BREAK = 31;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int LBRACK = 25;
  public static final int GREATEREQUAL = 44;
  public static final int COLON = 30;
  public static final int LBRACE = 3;
  public static final int ELSE = 19;
  public static final int POINT = 51;
  public static final int READ = 35;
  public static final int ENUM = 20;
  public static final int RBRACK = 26;
  public static final int GOTO = 23;
  public static final int WHILE = 34;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 28;
  public static final int PROG = 2;
  public static final int AMPERSANDAMPERSAND = 40;
  public static final int PRINT = 12;
  public static final int DO = 33;
}

